# You are given string s of length n, having m wildcard 
# characters '?', where each wildcard character represent
# a single character. Write a program which returns list of 
# all possible distinct strings that can be generated by 
# replacing each wildcard characters in s with either '0' or '1'.

# Any string in returned list must not contain '?' character 
# i.e. you have to replace all '?' with either '0' or '1'.

possible_chars = [0,1]
def find_all_possibilities(input_string)
	find_all_possibilities_helper(input_string, 0, [])
end

def find_all_possibilities_helper(input_string, index_, result_array)
	return result_array if index_ == input_string.size

	if input_string[index_] == '?'
		possible_chars.each_with_index do |char, i|
			# find_all_possibilities_helper(input_string, index_ + 1, result_array)
		end
	elsif input_stirng
		find_all_possibilities_helper(input_string, index_ + 1, result_array)
	end
end

s = “1?10”
print find_all_possibilities(s)
#result = ["1010", "1110"] or ["1110", "1010"].